name: Keep Backend Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual triggering if needed

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to API
        run: curl -sS https://api.tawqielaqariya.com/api/properties > /dev/null
